title: Samuel Franciscus Togar Hasurungan
description: Portfolio Asesmen II-2100 KIPP

remote_theme: "just-the-docs/just-the-docs@v0.4.0" # Menggunakan tema dokumentasi terbaik

plugins:
  - jekyll-remote-theme
  - jekyll-relative-links

url: "https://sfrans21.github.io"
baseurl: "/ii2100_all-about-me"
